import amqp from 'amqplib';

export const RABBITMQ_DEFAULT_CHANNEL_NAME = process.env.RABBITMQ_DEFAULT_CHANNEL_NAME || 'defaultChannel';
export const RABBITMQ_DEFAULT_CHANNEL_EXCHANGE_NAME = process.env.RABBITMQ_DEFAULT_CHANNEL_EXCHANGE_NAME || 'defaultExchange';
export const RABBITMQ_DEFAULT_CHANNEL_EXCHANGE_TYPE = process.env.RABBITMQ_DEFAULT_CHANNEL_EXCHANGE_TYPE || 'direct';
export const RABBITMQ_DEFAULT_CHANNEL_EXCHANGE_DURABLE = process.env.RABBITMQ_DEFAULT_CHANNEL_EXCHANGE_DURABLE === 'true' || false;
export const RABBITMQ_DEFAULT_CHANNEL_QUEUE_NAME = process.env.RABBITMQ_DEFAULT_CHANNEL_QUEUE_NAME || 'defaultQueue';
export const RABBITMQ_DEFAULT_CHANNEL_QUEUE_DURABLE = process.env.RABBITMQ_DEFAULT_CHANNEL_QUEUE_DURABLE === 'true' || false;
export const RABBITMQ_DEFAULT_CHANNEL_QUEUE_ROUTE = process.env.RABBITMQ_DEFAULT_CHANNEL_QUEUE_ROUTE || 'defaultRoute';
export const RABBITMQ_DEFAULT_PREFETCH = parseInt(process.env.RABBITMQ_DEFAULT_PREFETCH || '1', 1);
export const RABBITMQ_DEFAULT_COPYCOUNT = parseInt(process.env.RABBITMQ_DEFAULT_COPYCOUNT || '1', 1);
export const RABBITMQ_RECONNECT_DELAY = parseInt(process.env.RABBITMQ_RECONNECT_DELAY || '1000', 1000);
export const RABBITMQ_URI = process.env.RABBITMQ_URI || 'amqp://localhost';
